import AppKit
import Foundation
import UniformTypeIdentifiers

enum ClipboardEntryKind: String, Codable, Sendable {
    case text
    case url
    case image
}

struct ClipboardEntry: Identifiable, Codable, Equatable, Sendable {
    let id: UUID
    let kind: ClipboardEntryKind
    let value: String
    let createdAt: Date

    init(id: UUID = UUID(), kind: ClipboardEntryKind, value: String, createdAt: Date = .now) {
        self.id = id
        self.kind = kind
        self.value = value
        self.createdAt = createdAt
    }
}

@MainActor
final class ClipboardManager {
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    var onEntriesChange: (([ClipboardEntry]) -> Void)?

    private(set) var entries: [ClipboardEntry] = [] {
        didSet { onEntriesChange?(entries) }
    }

    private var lastChangeCount = NSPasteboard.general.changeCount
    private var monitorTask: Task<Void, Never>?
    private var isWritingToPasteboard = false
    private let storageURL: URL

    init() {
        storageURL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            .appendingPathComponent("NotchFlow/clipboard.json")
        load()
    }

    func setMonitoringEnabled(_ enabled: Bool) {
        monitorTask?.cancel()
        monitorTask = nil
        guard enabled else { return }

        monitorTask = Task {
            while !Task.isCancelled {
                captureIfChanged()
                try? await Task.sleep(for: .seconds(1))
            }
        }
        captureIfChanged()
    }

    func captureIfChanged() {
        guard !isWritingToPasteboard else { return }

        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard !isConcealedPasteboard(pasteboard) else { return }

        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            appendNormalized(string, kind: clipboardKind(for: string))
            return
        }

        if let url = pasteboard.string(forType: NSPasteboard.PasteboardType(rawValue: "public.url")), !url.isEmpty {
            appendNormalized(url, kind: .url)
        }
    }

    func captureCurrentContents() {
        let pasteboard = NSPasteboard.general
        lastChangeCount = pasteboard.changeCount

        guard !isConcealedPasteboard(pasteboard) else { return }

        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            appendNormalized(string, kind: clipboardKind(for: string))
            return
        }

        if let url = pasteboard.string(forType: NSPasteboard.PasteboardType(rawValue: "public.url")), !url.isEmpty {
            appendNormalized(url, kind: .url)
        }
    }

    func copyBack(_ entry: ClipboardEntry) {
        let pasteboard = NSPasteboard.general
        isWritingToPasteboard = true
        pasteboard.clearContents()
        pasteboard.setString(entry.value, forType: .string)
        lastChangeCount = pasteboard.changeCount
        isWritingToPasteboard = false
    }

    func visibleEntries(isPremium: Bool) -> [ClipboardEntry] {
        let limit = isPremium ? NotchFlowConstants.premiumClipboardLimit : NotchFlowConstants.freeClipboardLimit
        return Array(entries.prefix(limit))
    }

    func setEntriesForTesting(_ entries: [ClipboardEntry]) {
        self.entries = entries
    }

    private func isConcealedPasteboard(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return Self.concealedTypes.contains { types.contains($0) }
    }

    private func appendNormalized(_ value: String, kind: ClipboardEntryKind) {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        let normalized = trimmed.count > 4_000 ? String(trimmed.prefix(4_000)) + "…" : trimmed
        append(ClipboardEntry(kind: kind, value: normalized))
    }

    private func clipboardKind(for value: String) -> ClipboardEntryKind {
        if let url = URL(string: value), let scheme = url.scheme?.lowercased(), ["http", "https", "ftp"].contains(scheme) {
            return .url
        }
        return .text
    }

    private func append(_ entry: ClipboardEntry) {
        entries.removeAll { $0.value == entry.value }
        entries.insert(entry, at: 0)
        if entries.count > NotchFlowConstants.premiumClipboardLimit {
            entries = Array(entries.prefix(NotchFlowConstants.premiumClipboardLimit))
        }
        persist()
    }

    private func persist() {
        do {
            let data = try JSONEncoder().encode(entries)
            try SecureFileWriter.write(data, to: storageURL)
        } catch {
            NotchFlowLog.storage.error("Failed to persist clipboard history: \(error.localizedDescription, privacy: .public)")
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: storageURL),
              let decoded = try? JSONDecoder().decode([ClipboardEntry].self, from: data) else { return }
        entries = decoded
    }
}
